### ISSUE TITLE
LaTeX2e 2023-11-01 provides a new zref-like label-ref system

### ISSUE THREAD

**Issue by muzimuzhi** [gusbrs/zref-clever#21]
I don't know if the new property-based cross-reference system provided by LaTeX2e 2023-11-01 can be a drop-in replacement of `zref`, so this issue is just a news sharing.

The new system is shortly described in `texdoc ltnews38` and documented in more detail in `texdoc lthproperties-doc`. It's source file is [`ltproperties.dtx`](https://github.com/latex3/latex2e/blob/develop/base/ltproperties.dtx).

**Comment by gusbrs** [comment]
I've seen it. It's pretty cool to see `l3reftmp.sty` be promoted to `ltproperties`. Ulrike has been working hard.  :-)
Thanks for the heads-up!

For reference, the question has been popping of late: https://github.com/gusbrs/zref-check/issues/2

**Comment by gusbrs** [comment]
No problem at all, quite the contrary. I really just thought linking the two was useful.  ;-)
Thanks again.
